version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          source ./venv/bin/activate
          pip install -r ./requirements.txt
          pip install wheel
          pip wheel -w /tmp/wheels -r ./requirements.txt ./
      - persist_to_workspace:
          root: /tmp/
          paths:
            - wheels
  release:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run: |
          git checkout release
          cp /tmp/wheels/foxy* ./wheels/
          git add $(git ls-files -o ./wheels)
          git commit -m "release"
          git push
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            branches:
              ignore: release
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
